import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Layout, Typography } from "antd";
import { Header, Content, Footer } from "antd/lib/layout/layout";
import Text from "antd/lib/typography/Text";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AntdRegistry>
          <Typography>
            <Layout>
              <Header style={{ display: "flex", alignItems: "center" }}>
                <Text style={{ color: "white" }}>Charts app</Text>
              </Header>
              <Content style={{ padding: "0 48px" }}>{children}</Content>
              <Footer style={{ textAlign: "center" }}>
                Ant Design ©{new Date().getFullYear()} Created by Juraj
                Kružliak
              </Footer>
            </Layout>
          </Typography>
        </AntdRegistry>
      </body>
    </html>
  );
}
